apiVersion: v1
data:
  FOO: d7dac920c9096b88
kind: ConfigMap
metadata:
  name: cm
  namespace: br
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-green
    app.kubernetes.io/region: europe-west4
    app.kubernetes.io/type: br
    environment: prod
  name: bluegreen-demo
  namespace: br
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: blue-green
    app.kubernetes.io/type: br
    environment: prod
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-green
    app.kubernetes.io/region: europe-west4
    app.kubernetes.io/type: br
    environment: prod
  name: bluegreen-demo-preview
  namespace: br
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: blue-green
    app.kubernetes.io/type: br
    environment: prod
  type: ClusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: sample
  namespace: br
spec:
  metrics:
  - name: sample
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - args:
                - -c
                - echo 'BOOM';exit 0;
                command:
                - /bin/sh
                image: busybox
                name: sample
              restartPolicy: Never
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: post-sample
  namespace: br
spec:
  metrics:
  - name: post-sample
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - args:
                - -c
                - echo 'BOOM! POST-TEST!';exit 0;
                command:
                - /bin/sh
                image: busybox
                name: post-sample
              restartPolicy: Never
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: blue-green
    app.kubernetes.io/region: europe-west4
    app.kubernetes.io/type: br
    environment: prod
  name: bluegreen-application
  namespace: br
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: blue-green
      app.kubernetes.io/type: br
      environment: prod
  strategy:
    blueGreen:
      activeService: bluegreen-demo
      autoPromotionEnabled: false
      postPromotionAnalysis:
        templates:
        - templateName: post-sample
      prePromotionAnalysis:
        templates:
        - templateName: sample
      previewService: bluegreen-demo-preview
  template:
    metadata:
      labels:
        app: blue-green
        app.kubernetes.io/region: europe-west4
        app.kubernetes.io/type: br
        environment: prod
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: cm
        image: rminz/br-application:prod@sha256:6bb3546fe8996df1b25cb4e81354113cc1903f41a87131cd779bcf7ccee5694a
        imagePullPolicy: Always
        name: br
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
