apiVersion: v1
data:
  FOO: 165d84ef8ed6c73a
kind: ConfigMap
metadata:
  name: cm
  namespace: br
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-green
    app.kubernetes.io/region: europe-west4
    app.kubernetes.io/type: br
    environment: prod
  name: bluegreen-demo
  namespace: br
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: blue-green
    app.kubernetes.io/type: br
    environment: prod
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-green
    app.kubernetes.io/region: europe-west4
    app.kubernetes.io/type: br
    environment: prod
  name: bluegreen-demo-preview
  namespace: br
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: blue-green
    app.kubernetes.io/type: br
    environment: prod
  type: ClusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: sample
  namespace: br
spec:
  metrics:
  - name: sample
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - args:
                - -c
                - echo 'BOOM';exit 1;
                command:
                - /bin/sh
                image: busybox
                name: sample
              restartPolicy: Never
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: blue-green
    app.kubernetes.io/region: europe-west4
    app.kubernetes.io/type: br
    environment: prod
  name: bluegreen-application
  namespace: br
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: blue-green
      app.kubernetes.io/type: br
      environment: prod
  strategy:
    blueGreen:
      activeService: bluegreen-demo
      autoPromotionEnabled: false
      prePromotionAnalysis:
        templates:
        - templateName: sample
      previewService: bluegreen-demo-preview
  template:
    metadata:
      labels:
        app: blue-green
        app.kubernetes.io/region: europe-west4
        app.kubernetes.io/type: br
        environment: prod
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: cm
        image: rminz/br-application:prod@sha256:721cfbf34c12a1aa23b917f616b18a12367a096dc4d180341e5e613e20e9964b
        imagePullPolicy: Always
        name: br
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
