apiVersion: v1
data:
  FOO: 1dc8ce3195cd8002
kind: ConfigMap
metadata:
  name: cm
  namespace: br
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-green
    app.kubernetes.io/region: europe-west4
    app.kubernetes.io/type: br
    environment: prod
  name: bluegreen-demo
  namespace: br
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: blue-green
    app.kubernetes.io/type: br
    environment: prod
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-green
    app.kubernetes.io/region: europe-west4
    app.kubernetes.io/type: br
    environment: prod
  name: bluegreen-demo-preview
  namespace: br
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: blue-green
    app.kubernetes.io/type: br
    environment: prod
  type: ClusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: blue-green
    app.kubernetes.io/region: europe-west4
    app.kubernetes.io/type: br
    environment: prod
  name: bluegreen-application
  namespace: br
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: blue-green
      app.kubernetes.io/type: br
      environment: prod
  strategy:
    blueGreen:
      activeService: bluegreen-demo
      autoPromotionEnabled: false
      previewService: bluegreen-demo-preview
  template:
    metadata:
      labels:
        app: blue-green
        app.kubernetes.io/region: europe-west4
        app.kubernetes.io/type: br
        environment: prod
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: cm
        image: rminz/br-application:prod@sha256:0d9e7ddb1f85356508859fd4638432f75aa4ce3738f3f00f2710384be3cf9ec2
        imagePullPolicy: Always
        name: br
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
