apiVersion: v1
data:
  FOO: fe5f0ae824e0bb35
kind: ConfigMap
metadata:
  name: cm-fe5f0ae824e0bb35
  namespace: br
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-green
    app.kubernetes.io/region: europe-west4
    app.kubernetes.io/type: br
    environment: prod
  name: bluegreen-demo
  namespace: br
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: blue-green
    app.kubernetes.io/type: br
    environment: prod
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-green
    app.kubernetes.io/region: europe-west4
    app.kubernetes.io/type: br
    environment: prod
  name: bluegreen-demo-preview
  namespace: br
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: blue-green
    app.kubernetes.io/type: br
    environment: prod
  type: ClusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: blue-green
    app.kubernetes.io/region: europe-west4
    app.kubernetes.io/type: br
    environment: prod
  name: bluegreen-application
  namespace: br
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: blue-green
      app.kubernetes.io/type: br
      environment: prod
  strategy:
    blueGreen:
      activeService: bluegreen-demo
      autoPromotionEnabled: false
      previewService: bluegreen-demo-preview
  template:
    metadata:
      labels:
        app: blue-green
        app.kubernetes.io/region: europe-west4
        app.kubernetes.io/type: br
        environment: prod
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: cm-fe5f0ae824e0bb35
        image: rminz/br-application:prod@sha256:851d00da0c9c88649c5c858bdaf16c63dc04c316d0d96ec037ca6e50fbbb54a9
        imagePullPolicy: Always
        name: br
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
