apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-green
    app.kubernetes.io/region: europe-west4
    app.kubernetes.io/type: br
    environment: prod
  name: bluegreen-demo
  namespace: br
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: blue-green
    app.kubernetes.io/type: br
    environment: prod
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-green
    app.kubernetes.io/region: europe-west4
    app.kubernetes.io/type: br
    environment: prod
  name: bluegreen-demo-preview
  namespace: br
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: blue-green
    app.kubernetes.io/type: br
    environment: prod
  type: ClusterIP
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: blue-green
    app.kubernetes.io/region: europe-west4
    app.kubernetes.io/type: br
    environment: prod
  name: bluegreen-application
  namespace: br
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: blue-green
      app.kubernetes.io/type: br
      environment: prod
  strategy:
    blueGreen:
      activeService: bluegreen-demo
      autoPromotionEnabled: false
      previewService: bluegreen-demo-preview
  template:
    metadata:
      labels:
        app: blue-green
        app.kubernetes.io/region: europe-west4
        app.kubernetes.io/type: br
        environment: prod
    spec:
      containers:
      - image: rminz/br-application:prod@sha256:ebe2313d7b8953bd731468c6c63e24f4ead41fa3f64dd4737e2d5e0b5137cff8
        imagePullPolicy: Always
        name: br
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
